### ISSUE TITLE
Output component does not return values in order of slider insertion

### ISSUE THREAD

**Issue by DambronOlivier** [MingboPeng/Colibri.Grasshopper#6]
hi @MingboPeng ,
amazing work with all the updates.

After testing, the outputs component seems to have the same previous issue than the iterator.
Though values are inserted in order of Names, the outputs do not correspond as following:
![outputsc](https://cloud.githubusercontent.com/assets/21184323/22312004/03cc58e0-e34e-11e6-8194-4581cbfa5975.PNG)

Olivier

**Comment by MingboPeng** [comment]
Hi Olivier, this is still the old one, I didn't updated any code of this yet. But thanks, I will try to fix this. Before I fix, you can use merge to collect all data first and then connect to values.
